export const CV_TEMPLATES = [
  { id: 'classic', name: 'Classic', blurb: 'Traditional single column with serif headings' },
  { id: 'modern', name: 'Modern', blurb: 'Two columns with a sidebar and accent color' },
  { id: 'minimal', name: 'Minimal', blurb: 'Clean spacing and light typography' },
  { id: 'elegant', name: 'Elegant', blurb: 'Navy and gold serif with a formal header' },
  { id: 'bold', name: 'Bold', blurb: 'Large type and strong black section bars' },
  { id: 'slate', name: 'Slate', blurb: 'Cool gray sidebar with a structured layout' },
  { id: 'timeline', name: 'Timeline', blurb: 'Vertical timeline for roles and dates' },
  { id: 'executive', name: 'Executive', blurb: 'Dark banner header for a corporate look' },
  { id: 'coral', name: 'Coral', blurb: 'Warm accent stripe and friendly spacing' },
  { id: 'compact', name: 'Compact', blurb: 'Dense two-column layout that fits more on a page' },
  { id: 'academic', name: 'Academic', blurb: 'Centered serif curriculum vitae style' },
  { id: 'midnight', name: 'Midnight', blurb: 'Dark page with teal highlights' },
  { id: 'editorial', name: 'Editorial', blurb: 'Magazine-like nameplate and skill tags' },
  { id: 'aurora', name: 'Aurora', blurb: 'Indigo banner with a soft violet page' },
  { id: 'forest', name: 'Forest', blurb: 'Deep green stripe and earthy serif type' },
  { id: 'mono', name: 'Mono', blurb: 'Typewriter spacing and monospaced text' },
  { id: 'frame', name: 'Frame', blurb: 'Double border like a formal certificate' },
  { id: 'split', name: 'Split', blurb: 'Terracotta panel on the left, content on the right' },
  { id: 'ribbon', name: 'Ribbon', blurb: 'Crimson band under the name' },
  { id: 'nordic', name: 'Nordic', blurb: 'Airy ice-blue page with thin rules' },
  { id: 'industrial', name: 'Industrial', blurb: 'Boxed sections with an orange accent' },
  { id: 'atelier', name: 'Atelier', blurb: 'Blush page and rounded, studio-like type' },
  { id: 'summit', name: 'Summit', blurb: 'Charcoal header with a gold ridge line' },
  { id: 'ocean', name: 'Ocean', blurb: 'Teal banner and a coastal, airy page' },
  { id: 'paper', name: 'Paper', blurb: 'Kraft-colored sheet with ink-stamp type' },
  { id: 'metro', name: 'Metro', blurb: 'Blue side stripe and city-grid headings' },
  { id: 'legal', name: 'Legal', blurb: 'Letterhead layout for a formal brief' },
  { id: 'canvas', name: 'Canvas', blurb: 'Gallery-white page with thin black rules' },
  { id: 'ember', name: 'Ember', blurb: 'Maroon banner and warm body text' },
  { id: 'harbor', name: 'Harbor', blurb: 'Navy left panel with nautical contrast' },
  { id: 'lumen', name: 'Lumen', blurb: 'Bright yellow accent on a clean white page' },
  { id: 'quartz', name: 'Quartz', blurb: 'Soft stone-gray type and muted rules' },
  { id: 'pulse', name: 'Pulse', blurb: 'Magenta header with high-contrast type' },
  { id: 'sage', name: 'Sage', blurb: 'Muted sage green with calm serif type' },
  { id: 'copper', name: 'Copper', blurb: 'Bronze banner and warm cream body' },
  { id: 'ink', name: 'Ink', blurb: 'Navy on cream, like a brush-and-ink sheet' },
  { id: 'glacier', name: 'Glacier', blurb: 'Icy white page with pale blue rules' },
  { id: 'orchid', name: 'Orchid', blurb: 'Lavender headings on a pale lilac page' },
  { id: 'cedar', name: 'Cedar', blurb: 'Wood-brown stripe and cream body' },
  { id: 'nova', name: 'Nova', blurb: 'Black header with electric blue accents' },
  { id: 'linen', name: 'Linen', blurb: 'Off-white sheet with olive highlights' },
  { id: 'carbon', name: 'Carbon', blurb: 'Graphite left panel and cool gray type' },
  { id: 'sunrise', name: 'Sunrise', blurb: 'Peach banner fading into a warm page' },
  { id: 'emerald', name: 'Emerald', blurb: 'Deep emerald banner with fresh mint accents' },
  { id: 'amber', name: 'Amber', blurb: 'Warm amber and honey tones with classic serif headings' },
  { id: 'cobalt', name: 'Cobalt', blurb: 'Bold cobalt blue stripe with crisp modern typography' },
  { id: 'terracotta', name: 'Terracotta', blurb: 'Warm earthen clay palette with refined editorial style' },
  { id: 'monaco', name: 'Monaco', blurb: 'Deep racing green left panel with gold detailing' },
  { id: 'fuchsia', name: 'Fuchsia', blurb: 'Vivid fuchsia header with high-contrast contemporary type' },
  { id: 'graphite', name: 'Graphite', blurb: 'Matte dark gray sheet with subtle titanium rules' },
  { id: 'nord', name: 'Nord', blurb: 'Arctic frost palette with cool slate and polar blue tags' },
  { id: 'crimson', name: 'Crimson', blurb: 'Deep scarlet left stripe and authoritative serif type' },
  { id: 'sandstone', name: 'Sandstone', blurb: 'Sun-baked sand tones with desert ochre accents' },
  { id: 'flare', name: 'Creative Flare', blurb: 'Vibrant sunset flare banner with artistic typography and pill tags' },
] as const

export type CvTemplateId = (typeof CV_TEMPLATES)[number]['id']

export function isCvTemplateId(value: unknown): value is CvTemplateId {
  return typeof value === 'string' && CV_TEMPLATES.some((item) => item.id === value)
}
